# Model
network: TMFNet
network_args: 
  num_classes: 2
  num_samples: 1000
  num_channels: 3
  embed_dim: 32
  pool_size: 50
  pool_stride: 15
  num_heads: 8
  fc_ratio: 4
  depth: 3
  attn_drop: 0.5
  fc_drop: 0.5

# Data
data_path: D:\DeepLearning\EEG-TransNet-main\dataset\raw
out_folder: output/bci_iv_2b

# Training
preferred_device: gpu
nGPU: 0
random_seed: 0

batch_size: 250

epochs: 1500

lr: 0.001

# Data augmentation
num_classes: 2
num_segs: 8
